[package]
name = "lets-encrypt-playground"
version = "0.1.0"
edition = "2018"
resolver = "2"

[dependencies]
async-std = "=1.8.0"
futures = "0.3.15"
log = "0.4.14"
rustls-acme = "0.1.6"
simple_logger = "1.11.0"
structopt = "0.3.21"
